const C={phone:"+91XXXXXXXXXX",wa:"91XXXXXXXXXX",email:"info@example.com",address:"Midoora, Awantipora, Jammu & Kashmir",hours:"Mon–Sat, 9:00 am – 3:00 pm (demo)",year:"2026–27",formEndpoint:"",
 principal:{name:"Mr. Demo Principal",msg:"Welcome to Modern Public Mission. Every child here is known by name, encouraged to ask questions, and supported to grow. We work closely with families so that school and home move together."},
 stats:[[28,"","Years of service"],[1200,"+","Students"],[45,"","Faculty members"],[12,"","Classes, Nursery to 10"]]};
// ===== demo art (inline SVG, no external images) =====
const PAL=[["#7dd3fc","#fde68a","#0f2a66"],["#fdba74","#fef3c7","#9a3412"],["#99f6e4","#e0f2fe","#0f766e"],["#c4b5fd","#fce7f3","#4338ca"],["#bbf7d0","#fef9c3","#15803d"]];
function scene(k,i=0){const p=PAL[i%5];let m="";
 if(k=="class")m=`<rect x="90" y="70" width="220" height="80" rx="6" fill="#14532d"/><rect x="100" y="80" width="200" height="60" fill="none" stroke="#fff" stroke-opacity=".5"/>${[0,1,2].map(n=>`<circle cx="${130+n*70}" cy="190" r="14" fill="#f1c9a5"/><rect x="${112+n*70}" y="204" width="36" height="21" rx="8" fill="${p[2]}"/>`).join("")}`;
 else if(k=="sport")m=`<circle cx="200" cy="130" r="36" fill="#fff" stroke="${p[2]}" stroke-width="4"/><path d="M200 94v72M164 130h72" stroke="${p[2]}" stroke-width="3"/><rect x="0" y="180" width="400" height="45" fill="#16a34a"/>`;
 else if(k=="event")m=`<rect x="70" y="150" width="260" height="50" rx="6" fill="${p[2]}"/>${[0,1,2,3,4].map(n=>`<path d="M${100+n*50} 60l7 16 17 2-13 11 4 17-15-9-15 9 4-17-13-11 17-2z" fill="#fbbf24"/>`).join("")}`;
 else if(k=="kids")m=[0,1,2,3].map(n=>`<circle cx="${110+n*60}" cy="${150-(n%2)*14}" r="19" fill="${["#f1c9a5","#d9a679","#f1c9a5","#c68e63"][n]}"/><path d="M${88+n*60} ${215} q0-42 22-42 q22 0 22 42z" fill="${p[2]}"/>`).join("");
 else m=`<rect x="120" y="96" width="160" height="90" fill="#fff"/><path d="M110 98l90-46 90 46z" fill="${p[2]}"/><rect x="186" y="136" width="28" height="50" fill="${p[2]}"/>${[140,242].map(x=>`<rect x="${x}" y="116" width="22" height="22" fill="#bae6fd"/>`).join("")}<path d="M200 52V24l24 8-24 8" fill="#f59e0b"/>`;
 return `<svg viewBox="0 0 400 225" role="img" aria-label="${k} illustration" xmlns="http://www.w3.org/2000/svg"><defs><linearGradient id="g${i}${k}" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="${p[0]}"/><stop offset="1" stop-color="${p[1]}"/></linearGradient></defs><rect width="400" height="225" fill="url(#g${i}${k})"/><circle cx="340" cy="46" r="22" fill="#fff" fill-opacity=".8"/><path d="M0 170l70-70 60 60 80-90 90 100 100-60v115H0z" fill="${p[2]}" fill-opacity=".28"/><path d="M0 195l90-50 90 40 100-60 120 70v30H0z" fill="${p[2]}" fill-opacity=".4"/>${m}</svg>`}
function avatar(i){const c=["#0f2a66","#b45309","#0d9488","#6d28d9","#be123c","#15803d"][i%6];const sk=["#f1c9a5","#d9a679","#c68e63"][i%3];return `<svg viewBox="0 0 200 200" role="img" aria-label="Demo portrait" xmlns="http://www.w3.org/2000/svg"><rect width="200" height="200" fill="${c}" fill-opacity=".16"/><circle cx="100" cy="78" r="38" fill="${sk}"/><path d="M62 70q38-48 76 0q-8-20-38-22q-30 2-38 22z" fill="#1f2937"/><path d="M30 200q0-62 70-62t70 62z" fill="${c}"/><path d="M84 142l16 22 16-22" fill="#fff"/></svg>`}
const ph=(k,i)=>`<div class="ph">${scene(k,i)}</div>`;
const faculty=[["Mr. Demo Principal","Principal","Leadership"],["Mrs. Demo Vice","Vice Principal","Leadership"],["Mr. Demo Math","Mathematics","Teaching"],["Ms. Demo Science","Science","Teaching"],["Mrs. Demo English","English","Teaching"],["Mr. Demo Social","Social Science","Teaching"],["Ms. Demo Office","Office Administrator","Administration"],["Mr. Demo Sports","Physical Education","Support"]];
const news=[["Admissions open for "+C.year,"Admissions","12 Mar 2026","Applications are open for Nursery to Class 9. Apply online or visit the campus.","campus"],["Annual Science & Art Exhibition","Event","28 Feb 2026","Students presented working models and artwork to parents and guests.","class"],["Parent–Teacher Meeting","Notice","15 Feb 2026","Families met class teachers to review progress and set goals for the term.","kids"]];
const vals=[["Care","Every child is known, supported and encouraged.","❤️"],["Learning","A strong JKBOSE foundation with curious, active classrooms.","📚"],["Integrity","Honesty and respect in everything we do.","⚖️"],["Safety","A secure, supportive campus families can trust.","🛡️"],["Communication","Open, regular contact between school and home.","💬"],["Growth","Academic, personal and social development together.","🌱"]];
const faq=[["Which curriculum is followed?","The school follows the JKBOSE curriculum."],["What documents are needed?","Demo: birth certificate, previous report card, passport photos and a parent ID. School to confirm."],["Is there a fee structure?","Demo: fee details will be shared at admission. School to confirm."]];
const nav=[["About","about"],["Academics","academics"],["Admissions","admissions"],["Faculty","faculty"],["Gallery","gallery"],["News","news"],["Contact","contact"]];
const $=s=>document.querySelector(s);
const cta=()=>`<section class="b"><div class="w rv"><div class="cta"><h2>Ready to begin your child's journey?</h2><p>Learn about admissions or start your application online.</p><div class="row"><a class="btn" href="#/admissions">Apply for Admission</a><a class="btn o" href="#/visit">Book a Campus Visit</a></div></div></div></section>`;
const hero=(t,p,c)=>`<section class="hero"><div class="w"><div><div class="crumb">Home / ${c||t}</div><h1>${t}</h1><p>${p}</p></div></div></section>`;
const cards=(a,f)=>`<div class="g3">${a.map((x,i)=>f(x,i)).join("")}</div>`;
const simple=(a)=>cards(a,(v,i)=>`<div class="card c${i%3+1} rv"><div class="ic">${v[2]||"✦"}</div><h3>${v[0]}</h3><p>${v[1]}</p></div>`);
const newsCard=(n,i)=>`<article class="card c${i%3+1} rv">${ph(n[4],i)}<span class="tag">${n[1]} · ${n[2]}</span><h3>${n[0]}</h3><p>${n[3]}</p></article>`;
const field=(id,l,t="text",req=1,x="")=>`<div><label for="${id}">${l}${req?' <span aria-hidden="true">*</span><span class="sk">required</span>':' (optional)'}</label><input id="${id}" name="${id}" type="${t}" ${req?'required':''} ${x} aria-describedby="${id}e"><p class="er" id="${id}e" role="alert"></p></div>`;
const sel=(id,l,o)=>`<div><label for="${id}">${l} <span aria-hidden="true">*</span></label><select id="${id}" name="${id}" required aria-describedby="${id}e"><option value="">Select…</option>${o.map(v=>`<option>${v}</option>`).join("")}</select><p class="er" id="${id}e" role="alert"></p></div>`;
const classes=["Nursery","LKG","UKG",...[1,2,3,4,5,6,7,8,9,10].map(n=>"Class "+n)];
const consent=`<div><label style="display:flex;gap:10px;align-items:flex-start;font-weight:400"><input id="consent" name="consent" type="checkbox" required style="width:24px;min-height:24px;margin-top:2px" aria-describedby="consente"> I agree that the school may contact me using these details. See the <a href="#/privacy">Privacy Policy</a>.</label><p class="er" id="consente" role="alert"></p></div>`;
const facCards=f=>cards(f,(x,i)=>`<article class="card c${i%3+1} rv"><div class="ph" style="border-radius:50%;width:120px;margin:0 auto 14px">${avatar(i)}</div><h3 style="text-align:center">${x[0]}</h3><p style="text-align:center">${x[1]} · ${x[2]}</p></article>`);

// ===== Parent portal (DEMO: client-side only; replace with real auth + backend) =====
let user=null,tick=null;
let CH=null;
const TT=[["9:00","English"],["9:45","Mathematics"],["10:30","Break"],["11:00","Science"],["11:45","Social Science"],["12:30","Games"]];
const NOTICES=[["Parent–Teacher Meeting","Saturday, 10 am. Please bring the diary."],["Annual Day practice","Class 5 students stay till 3:30 pm on Wednesday."],["Winter uniform","Winter uniform begins from 1 November."]];
const STU=[{id:"MPM1001",pw:"demo123",parent:"Mr. Demo Parent",name:"Aaliya Demo",cls:"Class 5-B",roll:"14",adm:"MPM-2021-0142",teacher:"Mrs. Demo English",att:"PPPPPPAPPPPPPPLPPPPPAPPPPPPP",res:"English:86;Mathematics:92;Science:88;Social Science:79;Urdu:90",fees:"Q1 Apr–Jun:₹6,000:Paid;Q2 Jul–Sep:₹6,000:Paid;Q3 Oct–Dec:₹6,000:Due 10 Oct"},
{id:"MPM1002",pw:"demo123",parent:"Mrs. Demo Guardian",name:"Zaid Demo",cls:"Class 8-A",roll:"7",adm:"MPM-2018-0075",teacher:"Mr. Demo Math",att:"PPPPPPPPPPLPPPPPPPPPPPPPPPPP",res:"English:74;Mathematics:81;Science:77;Social Science:70;Urdu:85",fees:"Q1 Apr–Jun:₹7,500:Paid;Q2 Jul–Sep:₹7,500:Paid;Q3 Oct–Dec:₹7,500:Paid"}];
const pr=t=>String(t||"").split(";").filter(Boolean).map(x=>x.split(":"));
const AT=()=>CH.att.split(""),RES=()=>pr(CH.res).map(x=>[x[0],+x[1]||0,100]),FEE=()=>pr(CH.fees);
const CAMS=[["Classroom 5-B","class",0],["Playground","sport",1],["Library","kids",2],["Activity Hall","event",3]];
function feed(k,i){const mv=[0,1,2].map(n=>`<circle r="9" cy="${150+n*14}" fill="#fff" fill-opacity=".85"><animate attributeName="cx" values="${60+n*40};${300-n*30};${60+n*40}" dur="${6+n*2}s" repeatCount="indefinite"/></circle>`).join("");
 return scene(k,i).replace("</svg>",`${mv}<rect width="400" height="225" fill="#000" fill-opacity=".12"/></svg>`)}
const stamp=()=>new Date().toLocaleString("en-IN",{hour12:false});
function loginView(){return hero("Parent Login","Secure access to your child's school information.","Parent Login")+`<section class="b"><div class="w"><div class="pt" style="max-width:860px"><form id="lf" novalidate class="card c2" style="max-width:none"><h3>Sign in</h3>${field("lu","Parent ID")}<div><label for="lp">Password <span aria-hidden="true">*</span></label><input id="lp" type="password" required autocomplete="current-password" aria-describedby="lpe"><p class="er" id="lpe" role="alert"></p></div><button class="btn" type="submit">Sign in</button><p class="er" id="lerr" role="alert"></p><p style="font-size:14px;color:var(--mu)">Forgot password? Contact the school office.</p></form>
<div class="card c3"><h3>Demo access</h3><p>Parent ID <strong>MPM1001</strong> or <strong>MPM1002</strong><br>Password <strong>demo123</strong></p><p class="note">Demo only. Real logins need a secure server, and camera streams need school approval and parent consent.</p></div></div></div></section>`}
function dashView(){const T=["Overview","Attendance","Results","Fees","Notices","Live Cameras"];
 return `<section class="hero" style="padding:32px 0"><div class="w"><div class="crumb">Parent Portal</div><h1 style="font-size:clamp(26px,4vw,38px)">Welcome, ${CH.parent}</h1></div></section><section class="b" style="padding-top:28px"><div class="w pt">
 <aside class="card side me c1"><div class="ph">${avatar(3)}</div><h3 style="margin:0">${CH.name}</h3><p>${CH.cls} · Roll ${CH.roll}</p><div class="kv"><b>Admission</b><span>${CH.adm}</span><b>Class teacher</b><span>${CH.teacher}</span><b>Year</b><span>${C.year}</span></div><button class="btn o" id="lo" style="margin-top:16px;width:100%">Sign out</button></aside>
 <div><div class="tabs" role="group" aria-label="Portal sections">${T.map((t,i)=>`<button type="button" data-t="${t}" aria-pressed="${i==0}">${t}</button>`).join("")}</div><div id="tc"></div></div></div></section>`}
function tab(t){const r=a=>`<div class="tbw"><table class="tb">${a}</table></div>`;let h="";
 if(t=="Overview"){const avg=Math.round(RES().reduce((a,x)=>a+x[1],0)/(RES().length||1));h=cards([["Attendance",Math.round(AT().filter(x=>x!="A").length/AT().length*100)+"%","Last 28 school days"],["Average marks",avg+"%","Latest term"],["Next fee",(FEE().find(x=>x[2]!="Paid")||["","—"])[1],(FEE().find(x=>x[2]!="Paid")||["","","All paid"])[2]]],(x,i)=>`<div class="card c${i+1}"><p>${x[0]}</p><div class="n" style="font-size:40px">${x[1]}</div><p>${x[2]}</p></div>`)+`<div class="card" style="margin-top:18px"><h3>Today's timetable</h3>${r(TT.map(x=>`<tr><td>${x[0]}</td><td>${x[1]}</td></tr>`).join(""))}</div>`}
 if(t=="Attendance")h=`<div class="card"><h3>Last 28 school days</h3><div class="dots" role="img" aria-label="Attendance calendar">${AT().map(x=>`<i class="${x=="A"?"a":x=="L"?"l":""}" title="${x=="P"?"Present":x=="A"?"Absent":"Late"}"></i>`).join("")}</div><p style="margin-top:12px">Teal present · Amber late · Red absent</p></div>`;
 if(t=="Results")h=`<div class="card"><h3>Term 2 marks</h3>${r("<tr><th>Subject</th><th>Marks</th><th>Progress</th></tr>"+RES().map(x=>`<tr><td>${x[0]}</td><td>${x[1]}/${x[2]}</td><td style="min-width:120px"><div class="sc"><i style="width:${x[1]}%"></i></div></td></tr>`).join(""))}</div>`;
 if(t=="Fees")h=`<div class="card"><h3>Fee status</h3>${r("<tr><th>Period</th><th>Amount</th><th>Status</th></tr>"+FEE().map(x=>`<tr><td>${x[0]}</td><td>${x[1]}</td><td><span class="bdg ${x[2]=="Paid"?"":"w"}">${x[2]}</span></td></tr>`).join(""))}<p style="margin-top:12px;color:var(--mu)">Online payment is not part of this demo.</p></div>`;
 if(t=="Notices")h=NOTICES.map((n,i)=>`<div class="card c${i%3+1}" style="margin-bottom:12px"><h3>${n[0]}</h3><p>${n[1]}</p></div>`).join("");
 if(t=="Live Cameras")h=`<p class="note">Demo: these are simulated feeds. Live access is shown only for your child's own areas, during school hours, with the school's consent.</p><div class="cams">${CAMS.map((c,i)=>`<button type="button" class="cam" data-c="${i}" aria-label="Open camera: ${c[0]}">${feed(c[1],c[2])}<div class="ov"><span class="live">LIVE</span><span class="ts">${stamp()}</span></div><span class="nm">${c[0]}</span></button>`).join("")}</div>`;
 $("#tc").innerHTML=h;document.querySelectorAll(".cam").forEach(b=>b.onclick=()=>{const c=CAMS[+b.dataset.c];$("#lbc").innerHTML=feed(c[1],c[2]);$("#lbt").textContent=c[0]+" · LIVE (demo)";$("#lb").returnTo=b;$("#lb").showModal()})}
function portal(){clearInterval(tick);const f=$("#lf");
 if(f)f.onsubmit=e=>{e.preventDefault();const u=$("#lu").value.trim(),p=$("#lp").value;[["lu",u],["lp",p]].forEach(([id,v])=>{const er=document.getElementById(id+"e");er.textContent=v?"":"Please fill in this field."});if(!u||!p)return;
  const st=STU.find(x=>x.id.toUpperCase()==u.toUpperCase()&&x.pw==p);if(st){CH=st;user=u;$("#app").innerHTML=pages.portal();portal()}else $("#lerr").textContent="Parent ID or password is incorrect."};
 if($("#lo")){$("#lo").onclick=()=>{user=null;CH=null;clearInterval(tick);$("#app").innerHTML=pages.portal();portal()};
  document.querySelectorAll("[data-t]").forEach(b=>b.onclick=()=>{document.querySelectorAll("[data-t]").forEach(x=>x.setAttribute("aria-pressed",x===b));tab(b.dataset.t)});tab("Overview");
  tick=setInterval(()=>document.querySelectorAll(".ts").forEach(x=>x.textContent=stamp()),1000)}}

// ===== Office (admin) console + persistence. DEMO: saves in this browser only =====
const G=[["campus","Main campus"],["class","Classroom"],["sport","Sports day"],["event","Annual day"],["kids","Students"],["campus","School gate"],["class","Science lab"],["sport","Playground"]];
const SUBS=[],K="mpm_demo_v1";
const rep=(a,b)=>Array.isArray(b)&&a.splice(0,a.length,...b);
try{const r=JSON.parse(localStorage.getItem(K)||"null");if(r){Object.assign(C,r.C);rep(faculty,r.faculty);rep(news,r.news);rep(CAMS,r.CAMS);rep(G,r.G);rep(NOTICES,r.NOTICES);rep(STU,r.STU);rep(SUBS,r.SUBS)}}catch(e){}
const save=()=>{try{localStorage.setItem(K,JSON.stringify({C,faculty,news,CAMS,G,NOTICES,STU,SUBS}))}catch(e){}};
let office=false,cur="Dashboard";
const esc=v=>String(v??"").replace(/&/g,"&amp;").replace(/"/g,"&quot;").replace(/</g,"&lt;");
const KINDS=["campus","class","sport","event","kids"];
const SCH={News:{a:news,f:[[0,"Title"],[1,"Category"],[2,"Date"],[3,"Summary","area"],[4,"Picture","sel",KINDS]],n:()=>["New post","News","Add date","Write a summary","campus"],t:x=>x[0]},
Faculty:{a:faculty,f:[[0,"Name"],[1,"Role / subject"],[2,"Group","sel",["Leadership","Teaching","Administration","Support"]]],n:()=>["New name","Role","Teaching"],t:x=>x[0]},
Gallery:{a:G,f:[[0,"Picture","sel",KINDS],[1,"Caption"]],n:()=>["campus","New photo"],t:x=>x[1]},
Notices:{a:NOTICES,f:[[0,"Title"],[1,"Message","area"]],n:()=>["New notice","Details"],t:x=>x[0]},
"Students & Parents":{a:STU,f:[["name","Student name"],["cls","Class"],["roll","Roll no."],["adm","Admission no."],["teacher","Class teacher"],["parent","Parent name"],["id","Parent login ID"],["pw","Parent password"],["att","Attendance (P present, A absent, L late)"],["res","Marks (Subject:marks;Subject:marks)","area"],["fees","Fees (Period:Amount:Status;…)","area"]],n:()=>({id:"MPM"+(1001+STU.length),pw:"change-me",parent:"",name:"New student",cls:"",roll:"",adm:"",teacher:"",att:"PPPPPPPPPP",res:"English:0",fees:""}),t:x=>x.name+" · "+x.id},
Cameras:{a:CAMS,f:[[0,"Camera name"],[1,"Scene","sel",KINDS],[2,"Style (0 to 4)","num"]],n:()=>["New camera","class",0],t:x=>x[0]}};
const OT=["Dashboard","Settings","News","Faculty","Gallery","Notices","Students & Parents","Cameras","Submissions"];
const gp=(p)=>p.split(".").reduce((o,k)=>o?.[k],C),sp=(p,v)=>{const k=p.split(".");const l=k.pop();k.reduce((o,x)=>o[x],C)[l]=/^stats\.\d\.0$/.test(p)?(+v||0):v};
function officeLogin(){return hero("Office Login","For authorised school staff only.","Office Login")+`<section class="b"><div class="w"><div class="pt" style="max-width:860px"><form id="of" novalidate class="card c1" style="max-width:none"><h3>Staff sign in</h3>${field("ou","Office ID")}<div><label for="op">Password <span aria-hidden="true">*</span></label><input id="op" type="password" required autocomplete="current-password" aria-describedby="ope"><p class="er" id="ope" role="alert"></p></div><button class="btn" type="submit">Sign in</button><p class="er" id="oerr" role="alert"></p></form><div class="card c3"><h3>Demo access</h3><p>Office ID <strong>admin</strong><br>Password <strong>office123</strong></p><p class="note">Demo only. A real launch needs secure staff accounts and a database.</p></div></div></div></section>`}
function officeView(){return `<section class="hero" style="padding:32px 0"><div class="w"><div class="crumb">Office Console</div><h1 style="font-size:clamp(26px,4vw,38px)">Manage the website</h1></div></section><section class="b" style="padding-top:28px"><div class="w"><div class="tabs" role="group" aria-label="Office sections">${OT.map(t=>`<button type="button" data-o="${t}" aria-pressed="${t==cur}">${t}</button>`).join("")}<button type="button" class="btn o" id="oo" style="min-height:44px;padding:8px 18px">Sign out</button></div><div id="oc" style="margin-top:20px"></div></div></section>`}
function subsView(){if(!SUBS.length)return `<p class="note">No submissions yet. Send a form on the site (application, visit, contact or feedback) and it appears here.</p>`;
 const sm=x=>Object.values(x.data).filter(v=>v&&v!==true).join(" · ").slice(0,140);
 const csv=["type,date,ref,details"].concat(SUBS.map(x=>[x.type,x.date,x.ref||"",JSON.stringify(x.data)].map(v=>'"'+String(v).replace(/"/g,'""')+'"').join(","))).join("\n");
 return `<div class="card"><div class="tbw"><table class="tb"><tr><th>Type</th><th>Date</th><th>Ref</th><th>Details</th></tr>${SUBS.map(x=>`<tr><td>${esc(x.type)}</td><td>${esc(x.date)}</td><td>${esc(x.ref||"")}</td><td>${esc(sm(x))}</td></tr>`).join("")}</table></div></div><div class="card" style="margin-top:14px"><h3>Export (CSV)</h3><textarea id="csv" rows="5" readonly aria-label="CSV export">${esc(csv)}</textarea><button class="btn" id="cp" style="margin-top:10px">Copy CSV</button> <button class="btn o" id="cl" style="margin-top:10px">Clear all</button></div>`}
const inp=(attr,l,v,ty,o)=>`<label style="display:block;font-weight:600;font-size:14px">${l}${ty=="area"?`<textarea ${attr} rows="3">${esc(v)}</textarea>`:ty=="sel"?`<select ${attr}>${o.map(x=>`<option${x==v?" selected":""}>${x}</option>`).join("")}</select>`:`<input ${attr} type="${ty=="num"?"number":"text"}" value="${esc(v)}">`}</label>`;
function otab(t){cur=t;document.querySelectorAll("[data-o]").forEach(x=>x.setAttribute("aria-pressed",x.dataset.o==t));let h="";
 if(t=="Dashboard")h=cards([["Students",STU.length],["News posts",news.length],["Faculty",faculty.length],["Submissions",SUBS.length]],(x,i)=>`<div class="card c${i%3+1}"><p>${x[0]}</p><div class="n" style="font-size:40px">${x[1]}</div></div>`)+`<p class="note">Demo console: changes are saved in this browser only. A real launch needs a database and secure staff accounts.</p><button class="btn o" id="rst">Reset all demo data</button>`;
 else if(t=="Settings")h=`<div class="card" style="display:grid;gap:12px"><h3>School details</h3>${[["phone","Phone"],["wa","WhatsApp (digits with country code)"],["email","Email"],["address","Address"],["hours","Opening hours"],["year","Academic year"],["principal.name","Principal name"],["principal.msg","Principal message","area"]].map(f=>inp(`data-s="${f[0]}"`,f[1],gp(f[0]),f[2])).join("")}<h3 style="margin-top:8px">Homepage numbers</h3>${C.stats.map((x,i)=>`<div class="two">${inp(`data-s="stats.${i}.0"`,"Number",x[0],"num")}${inp(`data-s="stats.${i}.1"`,"Suffix (e.g. +)",x[1])}${inp(`data-s="stats.${i}.2"`,"Label",x[2])}</div>`).join("")}</div>`;
 else if(t=="Submissions")h=subsView();
 else{const m=SCH[t];h=`<button class="btn" id="add">+ Add new</button><div style="margin-top:14px;display:grid;gap:10px">${m.a.map((x,j)=>`<details class="card" data-j="${j}"><summary>${esc(m.t(x))}</summary><div style="display:grid;gap:12px;margin-top:12px">${m.f.map(([k,l,ty,o])=>inp(`data-k="${k}"`,l,x[k],ty,o)).join("")}<button type="button" class="btn o" data-del="${j}">Delete</button></div></details>`).join("")}</div>`}
 $("#oc").innerHTML=h}
function officeInit(){const f=$("#of");
 if(f)f.onsubmit=e=>{e.preventDefault();const u=$("#ou").value.trim(),p=$("#op").value;$("#oue").textContent=u?"":"Please fill in this field.";$("#ope").textContent=p?"":"Please fill in this field.";if(!u||!p)return;if(u=="admin"&&p=="office123"){office=true;cur="Dashboard";$("#app").innerHTML=pages.office();officeInit()}else $("#oerr").textContent="Office ID or password is incorrect."};
 if(!$("#oo"))return;$("#oo").onclick=()=>{office=false;$("#app").innerHTML=pages.office();officeInit()};
 document.querySelectorAll("[data-o]").forEach(b=>b.onclick=()=>otab(b.dataset.o));
 $("#oc").oninput=ev=>{const el=ev.target;if(el.dataset.s){let v=el.value;sp(el.dataset.s,v);hdr();save();return}
  const d=el.closest("[data-j]");if(!d||el.dataset.k===undefined)return;const m=SCH[cur],it=m.a[+d.dataset.j];it[el.dataset.k]=el.type=="number"?+el.value:el.value;d.querySelector("summary").textContent=m.t(it);save()};
 $("#oc").onclick=ev=>{const b=ev.target.closest("button");if(!b)return;const sure=()=>{if(b.dataset.sure)return true;b.dataset.sure=1;b.textContent="Click again to confirm";return false};
  if(b.id=="add"){SCH[cur].a.push(SCH[cur].n());save();otab(cur)}
  else if(b.dataset.del!==undefined){if(sure()){SCH[cur].a.splice(+b.dataset.del,1);save();otab(cur)}}
  else if(b.id=="rst"){if(sure()){try{localStorage.removeItem(K)}catch(e){}location.reload()}}
  else if(b.id=="cl"){if(sure()){SUBS.length=0;save();otab(cur)}}
  else if(b.id=="cp"){const t=$("#csv");navigator.clipboard?.writeText(t.value).then(()=>b.textContent="Copied").catch(()=>{t.select();b.textContent="Press Ctrl+C"})}};
 otab(cur)}
const pages={
portal:()=>user?dashView():loginView(),office:()=>office?officeView():officeLogin(),
"":()=>`<section class="hero big"><div class="w"><div><span class="pill">Admissions open for ${C.year}</span><h1>A Caring Place to <em>Learn, Grow</em> and Thrive.</h1><p>In Midoora, Awantipora, Modern Public Mission offers JKBOSE education with caring teachers, open communication with parents, and a safe, supportive campus.</p><div class="row"><a class="btn" href="#/admissions">Apply for Admission</a><a class="btn o" href="#/visit">Book a Campus Visit</a></div><div class="chips"><span>✓ JKBOSE curriculum</span><span>✓ Caring teachers</span><span>✓ Safe campus</span></div></div><div class="art">${scene("campus",0)}</div></div></section>
<div class="tk" aria-label="Announcements"><div>${[1,2].map(()=>`<span>🎓 Admissions open for ${C.year}</span><span>📅 Campus visits by appointment</span><span>📱 Parent Portal with live updates</span><span>🏫 JKBOSE curriculum, Nursery to Class 10</span>`).join("")}</div></div>
<section class="stats"><div class="w"><div class="g3">${C.stats.map(s=>`<div><div class="n" data-n="${s[0]}" data-s="${s[1]}">${s[0]}${s[1]}</div><div>${s[2]}</div></div>`).join("")}</div></div></section>
<section class="b"><div class="w"><div class="eyebrow">Our foundations</div><h2>Six values behind every school day</h2>${simple(vals)}</div></section>
<section class="b alt"><div class="w rv"><div class="pr"><div class="ph">${avatar(0)}</div><div><div class="eyebrow">Principal's welcome</div><blockquote>“We nurture character alongside curriculum.”</blockquote><p class="lead">${C.principal.msg}</p><p><strong>${C.principal.name}</strong>, Principal · <a href="#/about">Read more about us</a></p></div></div></div></section>
<section class="b"><div class="w"><div class="eyebrow">Why us</div><h2>Why families choose Modern Public Mission</h2>${simple([["Caring teachers","Educators who know each child.","🧑‍🏫"],["Parent communication","Regular updates, easy contact.","📱"],["JKBOSE curriculum","A recognised, structured syllabus.","🎓"],["Safe environment","A supportive place to learn.","🏫"]])}</div></section>
<section class="b alt"><div class="w"><div class="eyebrow">Campus updates</div><h2>Latest news</h2>${cards(news,newsCard)}<p><a class="btn o" href="#/news" style="margin-top:22px">View all news &amp; events</a></p></div></section>${cta()}`,
about:()=>hero("About Modern Public Mission","A caring, JKBOSE-affiliated school in Midoora, Awantipora.","About")+`<section class="b"><div class="w"><div class="g3" style="grid-template-columns:repeat(auto-fit,minmax(300px,1fr));align-items:center"><div class="art" style="transform:none">${scene("campus",1)}</div><div><h2>Our story</h2><p class="lead">Demo text: Modern Public Mission has served the families of Midoora and Awantipora for 28 years, growing from a small neighbourhood school into a community of over 1,200 students.</p></div></div>${simple([["Mission","To give every child a caring, high-quality education.","🎯"],["Vision","Confident, curious learners who contribute to their community.","🔭"],["Philosophy","Education that supports students academically and personally.","🌟"]])}</div></section>`+cta(),
academics:()=>hero("Academics","Following the JKBOSE curriculum.","Academics")+`<section class="b"><div class="w">${simple([["JKBOSE curriculum","Structured learning aligned to the board syllabus.","📘"],["Class structure","Nursery to Class 10 (demo).","🏫"],["Teaching approach","Clear teaching, regular feedback, individual attention.","🧑‍🏫"],["Assessment","Regular tests and termly progress reports (demo).","📝"],["Co-curricular","Sports, arts and activities alongside academics.","🎨"]])}<h2 style="margin-top:40px">FAQ</h2>${faq.map(f=>`<details><summary>${f[0]}</summary><p>${f[1]}</p></details>`).join("")}</div></section>`+cta(),
admissions:()=>hero("Admissions "+C.year,"Everything you need to apply, in one place.","Admissions")+`<section class="b"><div class="w"><h2>How admission works</h2><ol class="steps">${["Explore the school","Check eligibility","Submit application","School review","We contact you or you visit","Admission confirmation"].map(s=>`<li><strong>${s}</strong></li>`).join("")}</ol><p class="note">Demo process. Eligibility, documents, dates and fees must be confirmed by the school.</p>
<h2 style="margin-top:32px">Apply online</h2><form id="af" novalidate><fieldset><legend>Parent / guardian</legend>${field("pn","Full name")}${field("pp","Phone number","tel",1,'inputmode="tel" autocomplete="tel"')}${field("pe","Email","email",0)}${sel("pr","Relationship to student",["Mother","Father","Guardian","Other"])}</fieldset>
<fieldset><legend>Student</legend>${field("sn","Student's full name")}${field("sd","Date of birth","date")}${field("ps","Current / previous school","text",0)}<div class="two">${sel("sc","Class applying for",classes)}${sel("ay","Academic year",[C.year])}</div></fieldset>
<fieldset><legend>Contact</legend>${field("ad","Address")}${sel("cm","Preferred contact method",["Phone call","WhatsApp","Email"])}<div><label for="ms">Message (optional)</label><textarea id="ms" name="ms" rows="3"></textarea></div></fieldset>${consent}<button class="btn" type="submit" id="sb">Submit application</button><div id="res" role="status" aria-live="polite"></div></form>
<p style="margin-top:24px"><a class="btn o" href="#/visit">Prefer to visit first? Book a campus visit</a></p></div></section>`,
visit:()=>hero("Book a Campus Visit","Meet our team and see the school.","Campus Visit")+`<section class="b"><div class="w"><form id="af" novalidate><fieldset><legend>Your details</legend>${field("pn","Parent / guardian name")}${field("pp","Phone number","tel",1,'inputmode="tel"')}${field("pe","Email","email",0)}${field("vd","Preferred date","date")}${sel("vt","Preferred time",["Morning","Late morning","Afternoon"])}${field("vn","Number of visitors","number",1,'min="1" max="10"')}${sel("sc","Student's intended class",classes)}<div><label for="ms">Message (optional)</label><textarea id="ms" name="ms" rows="3"></textarea></div></fieldset>${consent}<button class="btn" type="submit" id="sb">Request a visit</button><div id="res" role="status" aria-live="polite"></div></form></div></section>`,
faculty:()=>hero("Our Faculty","The people who teach and support your child.","Faculty")+`<section class="b"><div class="w"><div class="tabs" role="group" aria-label="Filter faculty">${["All","Leadership","Teaching","Administration","Support"].map((t,i)=>`<button type="button" data-f="${t}" aria-pressed="${i==0}">${t}</button>`).join("")}</div><div id="fl">${facCards(faculty)}</div><p class="note">Demo names and portraits.</p></div></section>`,
gallery:()=>hero("Gallery","School life, in pictures.","Gallery")+`<section class="b"><div class="w"><div class="gal">${G.map((g,i)=>`<button type="button" data-g="${g[0]}" data-i="${i}" aria-label="Open photo: ${g[1]}">${ph(g[0],i)}</button>`).join("")}</div><p class="note">Demo illustrations. Managed from Office Login.</p></div></section>`,
news:()=>hero("News & Events","Updates from the school.","News & Events")+`<section class="b"><div class="w">${cards(news.concat(news).slice(0,6),newsCard)}</div></section>`,
contact:()=>hero("Contact Us","We are happy to answer your questions.","Contact")+`<section class="b"><div class="w g3" style="grid-template-columns:repeat(auto-fit,minmax(300px,1fr))"><div class="card"><h3>Modern Public Mission</h3><p>${C.address}</p><p>Hours: ${C.hours}</p><p><a href="tel:${C.phone}">${C.phone}</a><br><a href="mailto:${C.email}">${C.email}</a></p><div class="row"><a class="btn g" href="https://wa.me/${C.wa}">Chat with us on WhatsApp</a><a class="btn o" href="https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(C.address)}" rel="noopener">Get directions</a></div></div>
<form id="af" novalidate class="card c2">${field("pn","Your name")}${field("pp","Phone number","tel",1,'inputmode="tel"')}<div><label for="ms">Message <span aria-hidden="true">*</span></label><textarea id="ms" rows="4" required aria-describedby="mse"></textarea><p class="er" id="mse" role="alert"></p></div><button class="btn" type="submit" id="sb">Send message</button><div id="res" role="status" aria-live="polite"></div></form></div></section>`,
privacy:()=>hero("Privacy Policy","How we handle your information.","Privacy")+`<section class="b"><div class="w"><p class="lead">Draft outline. The school's administrator or legal adviser must approve the final policy.</p>${["Information we collect","How we use it","Cookies and analytics","Data retention and security","Third-party services","Your rights","Contact us"].map(t=>`<h3>${t}</h3><p class="lead">[To be completed]</p>`).join("")}</div></section>`};
function nvr(){const h=location.hash.slice(2)||"";const a=nav.map(n=>`<a href="#/${n[1]}" ${h==n[1]?'aria-current="page"':''}>${n[0]}</a>`).join("");$("#nv").innerHTML=a;$("#mn").innerHTML=a+'<a href="#/portal">Parent Login</a><a href="#/office">Office Login</a><a class="btn" href="#/admissions">Apply for Admission</a><a class="btn o" href="#/visit">Book a Campus Visit</a>'}
function fx(){const A=(q,c)=>document.querySelectorAll(q).forEach(e=>e.classList.add("rv",...(c?[c]:[])));
 A(".b>.w>h2");A(".b>.w>.eyebrow");A(".b>.w>.lead");A(".g3>.card");A(".pr>.ph","rl");A(".pr>div:last-child","rr");A(".stats .g3>div","rz");A(".gal button","rz");A(".steps li");A("details");A(".art","rz");
 document.querySelectorAll(".g3,.steps,.gal,.cams").forEach(g=>[...g.children].forEach((c,i)=>c.style.setProperty("--i",Math.min(i,6))));
 const io=new IntersectionObserver(es=>es.forEach(x=>{if(!x.isIntersecting)return;x.target.classList.add("in");io.unobserve(x.target)}),{threshold:.12});document.querySelectorAll(".rv").forEach(r=>io.observe(r));
 const rm=matchMedia("(prefers-reduced-motion:reduce)").matches;document.querySelectorAll("[data-n]").forEach(el=>{if(rm)return;const T=+el.dataset.n,S=el.dataset.s;const io2=new IntersectionObserver(es=>{if(!es[0].isIntersecting)return;io2.disconnect();const t0=performance.now();(function st(t){const k=Math.min(1,(t-t0)/1400);el.textContent=Math.round(T*(1-Math.pow(1-k,3))).toLocaleString()+(k==1?S:"");if(k<1)requestAnimationFrame(st)})(t0)});io2.observe(el)})}
function route(first){clearInterval(tick);const h=location.hash.slice(2)||"";$("#app").innerHTML=(pages[h]||pages[""])();nvr();$("#mn").classList.remove("open");$("#mt").setAttribute("aria-expanded","false");
 document.title=(h?h[0].toUpperCase()+h.slice(1)+" | ":"")+"Modern Public Mission, Awantipora";if(!first){scrollTo(0,0);$("#app").focus({preventScroll:true})}
 const f=$("#af");if(f)f.onsubmit=submit;if(h=="portal")portal();if(h=="office")officeInit();
 document.querySelectorAll("[data-g]").forEach(b=>b.onclick=()=>{$("#lbc").innerHTML=scene(b.dataset.g,+b.dataset.i);$("#lbt").textContent="Demo photo: "+b.dataset.g;$("#lb").returnTo=b;$("#lb").showModal()});
 document.querySelectorAll("[data-f]").forEach(b=>b.onclick=()=>{document.querySelectorAll("[data-f]").forEach(x=>x.setAttribute("aria-pressed",x===b));const v=b.dataset.f;$("#fl").innerHTML=facCards(v=="All"?faculty:faculty.filter(x=>x[2]==v));fx()});fx()}
async function submit(ev){ev.preventDefault();const f=ev.target;let bad=null;
 f.querySelectorAll("input,select,textarea").forEach(i=>{const er=document.getElementById(i.id+"e");let m="";
  if(i.required&&(i.type=="checkbox"?!i.checked:!i.value.trim()))m=i.type=="checkbox"?"Please tick to continue.":"Please fill in this field.";
  else if(i.type=="tel"&&!/^[+\d][\d\s-]{8,14}$/.test(i.value.trim()))m="Enter a valid phone number, e.g. 98XXXXXXXX.";
  else if(i.type=="email"&&i.value&&!/^\S+@\S+\.\S+$/.test(i.value))m="Enter a valid email address.";
  if(er)er.textContent=m;i.setAttribute("aria-invalid",!!m);if(m&&!bad)bad=i});
 if(bad){bad.focus();return}
 const b=$("#sb");b.disabled=true;b.textContent="Sending…";const ref="MPM-"+Date.now().toString(36).toUpperCase();let ok=true;
 if(C.formEndpoint){try{const d=Object.fromEntries(new FormData(f));d.reference=ref;const r=await fetch(C.formEndpoint,{method:"POST",headers:{"Content-Type":"application/json",Accept:"application/json"},body:JSON.stringify(d)});ok=r.ok}catch(x){ok=false}}
 if(!ok){b.disabled=false;b.textContent="Try again";$("#res").innerHTML='<p class="er">Sorry, we could not send this. Please check your connection and try again, or WhatsApp us.</p>';return}
 const dd={};f.querySelectorAll("input,select,textarea").forEach(x=>dd[x.id]=x.type=="checkbox"?x.checked:x.value);SUBS.unshift({ref,type:location.hash.includes("visit")?"Campus visit":location.hash.includes("admissions")?"Application":"Contact",date:new Date().toLocaleString("en-IN"),data:dd});save();const v=location.hash.includes("visit");$("#res").innerHTML=`<div class="ok"><strong>Thank you.</strong> ${v?"Your visit request has been received. The school will contact you to confirm the date and time.":"Your submission has been received. The school team will contact you using the details provided."}<br>Reference: <strong>${ref}</strong>${C.formEndpoint?"":'<br><em>(Demo mode: connect a form endpoint to receive submissions.)</em>'}</div>`;b.textContent="Submitted"}
addEventListener("scroll",()=>{const d=document.documentElement,m=d.scrollHeight-innerHeight;$("#sp").style.width=(m>0?scrollY/m*100:0)+"%";document.querySelector("header").classList.toggle("hs",scrollY>8)},{passive:true});
$("#mt").onclick=()=>{const o=$("#mn").classList.toggle("open");$("#mt").setAttribute("aria-expanded",o);$("#mt").setAttribute("aria-label",o?"Close menu":"Open menu")};
$("#lbx").onclick=()=>$("#lb").close();$("#lb").onclose=()=>{const r=$("#lb").returnTo;if(r)r.focus()};
function hdr(){["#fp","#tp"].forEach(s=>{$(s).href="tel:"+C.phone;$(s).textContent=s=="#tp"?"Call us":C.phone});$("#fw").href="https://wa.me/"+C.wa;$("#fe").textContent=C.email}hdr();$("#yr").textContent=new Date().getFullYear();

// ===== review banner + feedback =====
$("#pbx").onclick=()=>$("#pb").remove();
$("#fbo").onclick=()=>{$("#fr").innerHTML="";$("#fb").showModal();$("#fc").focus()};$("#fx").onclick=()=>$("#fb").close();
$("#ff").onsubmit=async e=>{e.preventDefault();const c=$("#fc").value.trim();$("#fce").textContent=c?"":"Please add a comment.";if(!c){$("#fc").focus();return}
 const d={page:location.hash||"#/",area:$("#fa").value,name:$("#fn").value.trim()||"Anonymous",comment:c};SUBS.unshift({ref:"FB-"+Date.now().toString(36).toUpperCase(),type:"Feedback",date:new Date().toLocaleString("en-IN"),data:d});save();
 if(C.formEndpoint){try{const r=await fetch(C.formEndpoint,{method:"POST",headers:{"Content-Type":"application/json",Accept:"application/json"},body:JSON.stringify({type:"feedback",...d})});if(!r.ok)throw 0;$("#fr").innerHTML='<div class="ok">Thank you! Your feedback was sent.</div>';$("#ff").reset();return}catch(x){$("#fr").innerHTML='<p class="er">Could not send. Please try again.</p>';return}}
 const body=`Page: ${d.page}\nArea: ${d.area}\nFrom: ${d.name}\n\n${d.comment}`;
 $("#fr").innerHTML=`<div class="ok">Almost done. <a href="mailto:${C.email}?subject=${encodeURIComponent("Website prototype feedback")}&body=${encodeURIComponent(body)}">Click here to send it by email</a>.</div>`};
addEventListener("hashchange",()=>route());route(true);
